"""create migrations

Revision ID: 31e3fe943006
Revises: a75d3c790442
Create Date: 2026-02-03 13:15:22.357302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e3fe943006'
down_revision = 'a75d3c790442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
