"""empty message

Revision ID: c985274554e5
Revises: 249779eb0370
Create Date: 2026-02-05 12:55:43.208628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c985274554e5'
down_revision = '249779eb0370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_seats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('selected_days', sa.String(), nullable=True))

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_spots', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dropoff_spots', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('dropoff_spots')
        batch_op.drop_column('pickup_spots')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('selected_days')
        batch_op.drop_column('num_seats')

    # ### end Alembic commands ###
