"""add role to parents

Revision ID: 2308ac20a5f4
Revises: 71f927cc0cd2
Create Date: 2026-02-01 23:19:50.497541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2308ac20a5f4'
down_revision = '71f927cc0cd2'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'role',
                sa.String(length=20),
                nullable=False,
                server_default='user'
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
