"""added seats booked

Revision ID: b50627bc81c3
Revises: 6587a29f6a33
Create Date: 2026-02-04 22:47:59.426259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50627bc81c3'
down_revision = '6587a29f6a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_seats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('selected_days', sa.String(), nullable=True))

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_spots', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dropoff_spots', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('dropoff_spots')
        batch_op.drop_column('pickup_spots')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('selected_days')
        batch_op.drop_column('num_seats')

    # ### end Alembic commands ###
